base_url: '/ego'
title: 'The Organge+'
theme: 'doks'

# post pagination
paginate: 7
# post excerpt
summaryLength: 20

# google analytics
google_analytics: "UA-40665301-3" # example : UA-123-45
# disqus short name
disqus_shortname: "" # get your shortname form here : https://disqus.com


############################# Outputs ##############################
#[outputs]
#home = ["HTML", "RSS", "JSON"]

############################# Main Menu ########################
menus:
  main:
    - name: Docs
      url: /docs/prologue/introduction/
      weight: 10
    - name: Blog
      url: /blog/
      weight: 40

  social:
    - name: GitHub
      pre: >-
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0
        0 24 24" fill="none" stroke="currentColor" stroke-width="2"
        stroke-linecap="round" stroke-linejoin="round" class="feather
        feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0
        0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0
        0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09
        1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44
        7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: 'https://github.com/h-enk/doks'
      post: v0.1.0
      weight: 10
    - name: Twitter
      pre: >-
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0
        0 24 24" fill="none" stroke="currentColor" stroke-width="2"
        stroke-linecap="round" stroke-linejoin="round" class="feather
        feather-twitter"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0
        0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0
        20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>
      url: 'https://twitter.com/getdoks'
      weight: 20

  docs:
    - name: "Prologue"
      identifier: "prologue"
      url: "/docs/prologue"
      weight: 10
    - name: "Help"
      identifier: "help"
      url: "/docs/help"
      weight: 20

############################# Footer Menu ########################
  footer:
    - weight: 1
      url: "about/"
      name: "About me"


    - weight: 2
      url: "author/"
      name: "Authors"


############################## Plugins ##############################
# CSS Plugins
params:
  plugins:
    css:
      - "plugins/bootstrap/bootstrap.min.css"
      - "css/style.css"
      - "https://fonts.googleapis.com/css2?family=Mulish:wght@400;600;700&display=swap"
    js:
      - "plugins/jquery/jquery.min.js"
      - "plugins/bootstrap/bootstrap.min.js"
      - "plugins/search/fuse.min.js"
      - "plugins/search/mark.js"
      - "plugins/search/search.js"
      - "https://unpkg.com/eva-icons"

#################### default parameters ################################

  logo: "images/logo.png"
  logo_height: "35px"
  favicon: "images/favicon.png"
  # Meta data
  description: "Drinking orange juice is good for your health. Reading some orange code is good too :D"
  author: "Dung Nguyen"
  # contact form action
  contact_form_action: "#" # contact form works with https://formspree.io
  # search
  search: true
  # main section
  mainSections: ["blog"]
  # copyright
  copyright: "Blog by Dung Nguyen.Theme by [Gethugothemes](https://gethugothemes.com/)"

  # sidebar
  sidebar: false

# Preloader
  preloader:
    enable: false
    preloader: "" # use jpg, png, svg or gif format.


# Subscription
  subscription:
    enable: false
    # mailchimp subsciption
    mailchimp_form_action: "#" # replace this url with yours
    mailchimp_form_name: "#" # replace this code with yours
    title: "Subscribe for our monthly newsletter."
    input_placeholder: "Enter your email" 

# cookies
  cookies:
    enable: false
    expire_days: 2


  ## Homepage
  title: "Ego"
  titleSeparator: "-"
  titleAddition: "Ego - Static site generator for Alchemists"
  description: "Ego is a fast and easy to customize static site generator powered by Elixir"

  ## Open Graph
  images: ["doks.png"]
  ogLocale: "en_US"
  domainTLD: ""
  titleHome: "Ego static site generator"

  ## Twitter Cards
  twitterSite: "#"
  twitterCreator: "#"

  ## JSON-LD
  # schemaType: "Person"
  schemaType: "Organization"
  schemaName: "Ego"
  schemaAuthor: "Dung Nguyen"
  schemaAuthorTwitter: "https://twitter.com/henkverlinde"
  schemaAuthorLinkedIn: "https://www.linkedin.com/in/dung-nguyen-tien-695ba135/"
  schemaAuthorGitHub: "https://github.com/h-enk"
  schemaLocale: "en-US"
  schemaLogo: "logo-doks.png"
  schemaLogoWidth: 512
  schemaLogoHeight: 512
  schemaImage: "doks.png"
  schemaImageWidth: 1280
  schemaImageHeight: 640
  schemaTwitter: "https://twitter.com/getdoks"
  schemaLinkedIn: ""
  schemaGitHub: "https://github.com/h-enk/doks"
  schemaSection: "blog"

  ## Sitelinks Search Box
  siteLinksSearchBox: false

  ## Chrome Browser
  themeColor: "#fff"

  # Images
  quality: 85
  bgColor: "#fff"
  landscapePhotoWidths: [900, 800, 700, 600, 500]
  portraitPhotoWidths: [800, 700, 600, 500]
  lqipWidth: "20x"

  # Footer
  footer: "Powered by <a href=\"https://github.com/bluzky/ego/\">Ego</a>"
  copyright: "Copyright (c) 2021 Daniel Nguyen"

  # Alert
  alert: false
  alert_dismissable: true
  alert_text: "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

  # Edit Page
  docsRepo: "https://github.com/bluzky/ego"
  docsRepoBranch: "main/priv"
  editPage: true

  options:
    dark_mode: true
    collapsibleSidebar: true
